services:
  core_api:
    build:
      context: ./core_api
      dockerfile: Dockerfile.dev
    container_name: omni_stock_core_api_dev
    command: sh -c "tail -f /dev/null"
    volumes:
      - ./core_api:/usr/src/app:rw
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
